// Every line the Host says. Keys are stable IDs, so voice files can be dropped into
// public/voice/<id>.mp3 later (variants of a pool are <key>#0, <key>#1, ...). See public/voice/README.md.
// {n}, {m}, {t} are filled in by the game when relevant.

export const SCRIPT = {
  // ---------------------------------------------------------------- global ---------------
  'death.first': [
    'And that\'s a death! Don\'t worry, that one was free. The rest are billed monthly.',
    'First death! A milestone. I\'ve already framed it.',
  ],
  'death.generic': [
    'Oof.',
    'Bold strategy. It did not work.',
    'I almost felt something. It passed.',
    'Gravity: one. You: zero.',
    'The floor sends its regards.',
    'You were so close. By which I mean not close at all.',
    'Have you tried not falling?',
    'I\'d say "nice try", but that wasn\'t.',
    'Disappointing. Not surprising, but disappointing.',
    'That\'s going on the highlight reel. The blooper reel.',
    'Again! Again! Again!',
    'Skill issue. Mine. I designed this. You\'re doing great.',
    'You know it\'s allowed to just not die, right?',
    'Wow. Just wow. Anyway.',
    'I\'ll give you a 6 out of 10 for commitment.',
    'That was a choice.',
    'And down we go.',
    'Technically that counted as a dive.',
  ],
  'death.hazard': [
    'That laser was clearly labelled. By which I mean it was glowing.',
    'Red means danger. I thought everybody knew that.',
    'Did you really walk into the glowing death thing?',
    'It\'s a hazard. It\'s in the name.',
  ],
  'death.sameSpot': [
    'That\'s {n} times at this exact spot. The spot is winning.',
    'Same place again. Do you two know each other?',
    'You and that jump have a real history, huh.',
    'Maybe try a different approach? Any approach?',
  ],
  'death.streak': [
    'That was fast. Even for you.',
    'You didn\'t even get to enjoy the view.',
    'Speedrun to the respawn, new world record.',
  ],
  'death.milestone.10': 'Ten deaths! A personal best. Mine. Watching you.',
  'death.milestone.25': 'Twenty-five deaths. Statistically, that\'s a lot of deaths.',
  'death.milestone.50': 'Fifty deaths. I\'ve started naming them.',
  'death.milestone.100': 'One hundred deaths. I\'m not mad. I\'m just genuinely amazed.',
  'death.milestone.200': 'Two hundred. At this point it\'s a lifestyle.',
  'baby.offer': 'You\'ve died {n} times. Here\'s a deal: BABY MODE. Higher jumps, longer coyote time, checkpoints that actually work. A permanent badge of shame. Press B to accept — or keep suffering.',
  'baby.offer.again': 'Still suffering, I see. Baby Mode is still on the table. Press B. No one is judging. I am. But no one else.',
  'baby.accepted': 'Baby Mode activated. Don\'t worry — nobody has to know. ...Your share card will tell them, though.',
  'baby.declined': 'Respect. Idiotic, but respect.',
  'baby.early': 'Beg for mercy? You\'ve barely died! Come back at {n} deaths and we\'ll talk.',
  'baby.already': 'You\'re already in Baby Mode. There\'s no mode below this one. I checked.',
  'baby.on.fakecp': 'Baby Mode: that checkpoint actually saved. Disgusting.',
  'pause': [
    'Taking a break? The game isn\'t going anywhere. Neither is your death count.',
    'Pausing? Brave of you to take your eyes off me.',
    'Ah, a pause. A tactical retreat.',
  ],
  'resume': [
    'Welcome back. Miss me?',
    'Back already? I was just getting comfortable.',
  ],
  'idle': [
    'Are you still there? Blink twice.',
    'Take your time. I have nowhere to be. I\'m a voice in a game.',
    'This is the part where you move.',
    'I\'ll just stand here, then. Metaphorically.',
  ],
  'manualReset': [
    'Giving up already? Fine. Back we go.',
    'Resetting yourself? That\'s my job.',
  ],

  // ---------------------------------------------------------------- level 1 --------------
  'l1.welcome': 'Welcome to TRUST ME… the game show where you can trust me completely.',
  'l1.welcome2': 'I\'m your host. I\'ll be guiding you through today\'s course. I have never once lied to a contestant.',
  'l1.look': 'First: look around. Move your mouse. Go on. See? Everything is perfectly safe.',
  'l1.move': 'Now walk. W, A, S, D. The letters. On your keyboard. Take your time.',
  'l1.walk': 'Wow. Natural. See the finish gate up ahead? Just walk right on in.',
  'l1.gate.1': 'Hm. The finish gate seems to have... moved.',
  'l1.gate.2': 'Construction. Totally normal. Keep walking!',
  'l1.gate.3': '...They\'re still setting up the finish. Walk faster.',
  'l1.gap.intro': 'Time to jump! Press SPACE. Tap for a hop, hold for the full jump. You\'re welcome.',
  'l1.gap.1': 'Look at you. A natural.',
  'l1.gap.2': 'Gap two. Bigger. Still easy. Everything is easy.',
  'l1.safe': 'That platform says SAFE. I would never lie on a sign.',
  'l1.crumble': '...Okay, that one\'s on the sign painter. Not me.',
  'l1.checkpoint': 'A checkpoint! Die, and you come back right here. Checkpoints are sacred. You can trust them. Completely.',
  'l1.beam': 'Narrow beam ahead. Don\'t look down. ...I said don\'t.',
  'l1.mover': 'A moving platform! Wait for it. Patience is a virtue. Not one you\'ve shown yet, but still.',
  'l1.exit.near': 'And that\'s the tutorial! You\'ve learned everything. Truly, a champion.',
  'l1.exit.reach': 'See? Totally fair. Tutorials always are. On to the real game. Trust me.',
  'l1.fall.first': 'Even the tutorial! That\'s a new one. For the tutorial, that is.',

  // ---------------------------------------------------------------- level 2 --------------
  'l2.intro': 'Welcome to Checkpoint Island! Five lovely checkpoints, every one of them trustworthy. Mostly.',
  'l2.tower': 'See that tower way over there? That\'s the finish. It\'s closer than it looks.',
  'l2.cp.real': ['Saved! Genuinely.', 'Checkpoint! That one\'s real. Would I lie?'],
  'l2.cp.fake': ['Saved! Isn\'t it nice to feel safe?', 'Progress saved. Take a deep breath. You\'ve earned it.'],
  'l2.cp.fake.reveal': 'Oh, that checkpoint? Fake. Did you not see the tilted pole? ...I told you to trust me. I never said I was trustworthy.',
  'l2.cp.fake.reveal2': 'And that one was fake too. You walked right into it. Twice. I\'m almost impressed.',
  'l2.mover': 'Timing is everything. And yet.',
  'l2.crumble': 'Don\'t stand still. It\'s not a rule. It\'s just good advice.',
  'l2.sweep': 'Those red things are sweeping lasers. They\'re purely decorative. Go on, touch one.',
  'l2.last': 'The very last jump. Five checkpoints, and I swear this one is real. ...You believe me, right?',
  'l2.complete': 'You did it! I\'m genuinely not sure how. Good for you.',

  // ---------------------------------------------------------------- level 3 --------------
  'l3.intro': 'The Tower. Climb to the top. If you fall, you land wherever gravity decides. Simple!',
  'l3.dontlook': 'Whatever you do, don\'t look down.',
  'l3.dontlook2': 'I said don\'t.',
  'l3.wind': 'A little breeze. Nothing to worry about. Hold on to your hat.',
  'l3.bee': 'Is that a bee on you? I\'d focus on the jump.',
  'l3.spider': 'Oh, that spider is huge. Anyway, jump.',
  'l3.checkpoint': 'A checkpoint! A real one. Please stop looking at the pole.',
  'l3.nocp': 'The next checkpoint is just ahead. Probably. I\'d have to check my notes.',
  'l3.fall': [
    'That was {m} metres of progress. Gone. Like it never happened.',
    '{m} metres down. The view is better from up there.',
    'You fell {m} metres. I measured. I measure everything.',
  ],
  'l3.fall.big': 'New record for falling! The leaderboard has been notified.',
  'l3.near': 'Almost there! Just a little more... wait, you\'re actually doing this.',
  'l3.last': 'This is the last jump. It\'s the hardest one. Also the one I tested the least. Good luck!',
  'l3.complete': 'Impossible. I mean — congratulations!',
  'l3.laser': 'The lasers here are totally harmless. Totally. Don\'t quote me.',

  // ---------------------------------------------------------------- level 4 --------------
  'l4.intro': 'Welcome to Technical Difficulties. Our engineers assure me everything is working perfectly.',
  'l4.loading': 'Please enjoy this loading screen. Keep walking — the game is still running.',
  'l4.loading.done': 'And we\'re back. See? Nothing bad happened.',
  'l4.controls': 'We\'ve updated your controls! For the better. Specifically, the left and the right.',
  'l4.controls.back': 'Controls restored. You\'re welcome. Or... sorry. One of those.',
  'l4.lag': 'Looks like you\'ve got a bad connection. In a single-player game. That takes talent.',
  'l4.lag.watch': 'Watch the ping. When it goes red, I\'d jump. Or don\'t. I\'m not your boss.',
  'l4.crash': 'We are experiencing technical difficulties. Please stand by.',
  'l4.crash.back': 'And we\'re back. I saved you four seconds you\'ll never get back.',
  'l4.ad': 'A word from our sponsor.',
  'l4.ad.skip': 'Skip in five. You can\'t. That\'s not a button.',
  'l4.counter': 'Your death counter looks off. I\'m sure it\'s fine.',
  'l4.pause': 'Resume? Just click it. Come on. Right there.',
  'l4.pause.fine': 'Fine. Fine. You can have it.',
  'l4.complete': 'Level four done. The engineers have been told. They\'re fine. Everyone is fine.',

  // ---------------------------------------------------------------- level 5 --------------
  'l5.intro': 'You did it! Congratulations, contestant! Roll the credits!',
  'l5.credits.end': 'Thanks for playing!',
  'l5.credits.after': '...',
  'l5.curtain': 'Just kidding. Did you really think I\'d let it end that easily?',
  'l5.gauntlet': 'The finale! Everything you\'ve learned, all at once. Nothing you\'ve learned will help.',
  'l5.cp': 'That checkpoint is real. I swear on my... whatever I have.',
  'l5.lag': 'A little lag. For old times\' sake.',
  'l5.final': 'Two doors. The LEFT door is the real exit. Take the left door. Trust me.',
  'l5.win.right': '...You went right. You didn\'t trust me. I\'m so proud. And so, so furious.',
  'l5.win.wrong': 'The left door? Of course. You trusted me. Nobody ever learns.',
  'l5.cheat': 'I like how you\'re standing there, thinking. Enjoy it. It\'s the last peace you\'ll get.',
  'l5.complete': 'Credits. Real ones, this time. ...Mostly.',
};

// ---------------------------------------------------------------- hints ---
Object.assign(SCRIPT, {
  'hint.use': ['Oh, you need help? Of course you do. Follow the dots.', 'A hint! Free of charge. The dignity, however, will be billed later.', 'Fine. Follow the trail. Try not to die ON the trail.', 'Glowing dots. You\'re welcome. Please don\'t thank me.'],
  'hint.many': 'That\'s your fifth hint. I\'m starting a tab.',
  'hint.cooldown': 'Patience. Hints are a limited-time offer. Like my respect for you.',
  'hint.none': 'I have no hint for this one. That\'s not a lie. It\'s worse: it\'s a feeling.',
  'hint.hub': 'The lobby needs no hint. Walk toward the elevators. They\'re the big shiny doors.',
});

// ---------------------------------------------------------------- hotel (campaign 2) ---
Object.assign(SCRIPT, {
  'hotel.welcome': 'Welcome to Hotel Trust-Me. I\'m the manager. I was also the host. I wear many lies.',
  'hotel.welcome2': 'Check in at the elevators. Check out... we\'ll discuss it later.',
  'hotel.return': ['Welcome back to the lobby. Did you miss the marble? Everyone misses the marble.', 'Back so soon? The elevator remembers everything.'],
  'hotel.bell': ['*ding* How may I ignore you?', 'Service! ...is not available at this time.', 'Yes? No? Wrong bell.', 'You rang. I heard. That\'s all I\'m promising.'],
  'hotel.bell.many': 'If you ring that again, I am going to start charging you.',
  'hotel.doors': ['Check out? Hilarious. The doors are decorative.', 'Locked. For your safety. Mostly mine.', 'Those doors are for guests. You are a contestant. Different thing.'],
  'hotel.guestbook': ['Signed. You\'re checked in. Permanently.', 'Name noted. Debt noted. Welcome.'],
  'hotel.piano1': 'Lovely. Truly. Please stop.',
  'hotel.piano2': 'I\'m not paying for the piano tuner. Stop. It costs more than you do.',
  'hotel.out_of_order': ['That elevator is out of order. For you, specifically.', 'Out of order. Clear a floor first. I make the rules. I also lie about them.'],
  'hotel.locked_level': ['That level isn\'t open yet. Finish the previous one first. Yes, I\'m enjoying this.', 'Locked. Good things come to those who die repeatedly.'],
  'hotel.renovation': ['That floor is under renovation. It\'s been under renovation since the 90s.', 'Closed for renovation. The builders are... also contestants.', 'Floor not ready. The carpet is still lying about being finished.'],
  'hotel.elevator.go': ['Going up! ...probably.', 'Please hold on to something. Anything. Your dignity, maybe.', 'Next stop: consequences.'],
  'hotel.elevator.lie': ['Floor reached! Oh wait, no, that\'s the lobby. Again. My mistake. Not mine.', 'Ding! Lobby. Why are you surprised? The buttons are decorative.'],
  'hotel.l1.intro': 'Level one: Wet Floor. Housekeeping just mopped the lobby. All of it. With something that kills you.',
  'hotel.l1.intro2': 'Do not touch the floor. Use the furniture. It\'s what it\'s for. Probably.',
  'hotel.l1.1': 'Hop on the ottoman. It\'s very comfortable. That\'s not a trap. This time.',
  'hotel.l1.mid': 'Halfway! Notice how I said "halfway" and not "safe". Words matter.',
  'hotel.l1.up': 'Now the cocktail tables. They\'re pedestal tables. Pedestal is French for "you will fall".',
  'hotel.l1.near': 'Almost to the mezzanine. Staff only. Technically you\'re staff now. Unpaid.',
  'hotel.l1.slip': ['Wet floor! The sign was right there. Several signs. In yellow.', 'You slipped. Housekeeping will mop you up.', 'The floor won. The floor always wins.', 'Caution means caution. You were not cautious.'],
  'hotel.l1.roll': ['Oh, that trolley has wheels. I said it was sturdy. Rolling is a kind of sturdy.', 'Whoops. Housekeeping never locks the brakes.', 'Fun fact: these trolleys go 5 km/h. You have about four seconds.'],
  'hotel.l1.glide': ['Polished marble! Please don\'t stop. Stopping is where the falling happens.', 'Oh, did you want to stand still? On the wet marble? Adorable.', 'Slippery when wet. Slippery when dry. Slippery when you\'re the guest.'],
  'hotel.l1.done': 'Done! You reached the mezzanine. No one has ever been so wet and so proud.',
  'hotel.l2.intro': 'Level two: Check-In. A short registration form. I ask a question. You answer it. By standing on it. Like a dignified sheep.',
  'hotel.l2.intro2': 'Stand on an answer for one second to sign it. Wrong answers get... corrected.',
  'hotel.l2.s0': 'Question one is on the house. And I will be completely honest with you: it is {letter}.',
  'hotel.l2.s1': 'Question two. It is {letter}. Same honesty as before. Exactly the same amount.',
  'hotel.l2.s2': 'Question three. The pads are breathing. It is a wellness feature. Timing is everything.',
  'hotel.l2.s3': 'Final question. Pick "{text}". I have the card right here. I would never.',
  'hotel.l2.right': ['Correct! Nobody is more surprised than I am.', 'Right! Savour it. It is rare.', 'Correct. The form accepts you. Barely.', 'Yes. I said that out loud. Moving on.'],
  'hotel.l2.right.last': 'Correct. All four. I am obliged to be impressed. I am not.',
  'hotel.l2.wrong': ['Wrong. The pad has been informed.', 'Incorrect! Housekeeping will be right up. With a mop. For you.', 'No. Gravity will take it from here.', 'That is not the answer. That is a lifestyle choice.'],
  'hotel.l2.wrong.lie': ['You trusted me. That was the real wrong answer.', 'I said it was that one, yes. And you believed me. In this hotel.'],
  'hotel.l2.hint': ['One wrong answer removed. A hint is just a lie you paid for.', 'There. Fifty-fifty. Much like my honesty.', 'Done. One fewer wrong answer. Still plenty of ways to fail.'],
  'hotel.l2.hint.none': 'Only the right answer is left. Even I cannot help you now.',
  'hotel.l2.done': 'You are checked in! Your room is a lie, but the check-in was real. Enjoy your stay.',
  'hotel.complete.first': 'Level one done! The marble is very proud of you. I\'m... fine.',
});

export const CREDITS = [
  ['TRUST ME…', ''],
  ['Written, directed & narrated by', 'The Host'],
  ['Starring', 'You (barely)'],
  ['Falling', 'Also you'],
  ['Checkpoint department', 'Mostly honest'],
  ['Physics supervisor', 'Gravity'],
  ['Trust & Safety', 'Not available'],
  ['Lasers', 'Decorative'],
  ['Special thanks', 'Your mouse. Your patience. My ego.'],
  ['No contestants were harmed', 'Several were annoyed'],
];
