// Every line the Host says. Keys are stable IDs, so voice files can be dropped into
// public/voice/<id>.mp3 later (variants of a pool are <key>#0, <key>#1, ...). See public/voice/README.md.
// {n}, {m}, {t} are filled in by the game when relevant.

export const SCRIPT = {
  // ---------------------------------------------------------------- global ---------------
  'death.first': [
    'And that\'s a death! Don\'t worry, that one was free. The rest are billed monthly.',
    'First death! A milestone. I\'ve already framed it.',
  ],
  'death.generic': [
    'Oof.',
    'Bold strategy. It did not work.',
    'I almost felt something. It passed.',
    'Gravity: one. You: zero.',
    'The floor sends its regards.',
    'You were so close. By which I mean not close at all.',
    'Have you tried not falling?',
    'I\'d say "nice try", but that wasn\'t.',
    'Disappointing. Not surprising, but disappointing.',
    'That\'s going on the highlight reel. The blooper reel.',
    'Again! Again! Again!',
    'Skill issue. Mine. I designed this. You\'re doing great.',
    'You know it\'s allowed to just not die, right?',
    'Wow. Just wow. Anyway.',
    'I\'ll give you a 6 out of 10 for commitment.',
    'That was a choice.',
    'And down we go.',
    'Technically that counted as a dive.',
  ],
  'death.hazard': [
    'That laser was clearly labelled. By which I mean it was glowing.',
    'Red means danger. I thought everybody knew that.',
    'Did you really walk into the glowing death thing?',
    'It\'s a hazard. It\'s in the name.',
  ],
  'death.sameSpot': [
    'That\'s {n} times at this exact spot. The spot is winning.',
    'Same place again. Do you two know each other?',
    'You and that jump have a real history, huh.',
    'Maybe try a different approach? Any approach?',
  ],
  'death.streak': [
    'That was fast. Even for you.',
    'You didn\'t even get to enjoy the view.',
    'Speedrun to the respawn, new world record.',
  ],
  'death.milestone.10': 'Ten deaths! A personal best. Mine. Watching you.',
  'death.milestone.25': 'Twenty-five deaths. Statistically, that\'s a lot of deaths.',
  'death.milestone.50': 'Fifty deaths. I\'ve started naming them.',
  'death.milestone.100': 'One hundred deaths. I\'m not mad. I\'m just genuinely amazed.',
  'death.milestone.200': 'Two hundred. At this point it\'s a lifestyle.',
  'baby.offer': 'You\'ve died {n} times. Here\'s a deal: BABY MODE. Higher jumps, longer coyote time, checkpoints that actually work. A permanent badge of shame. Press B to accept — or keep suffering.',
  'baby.offer.again': 'Still suffering, I see. Baby Mode is still on the table. Press B. No one is judging. I am. But no one else.',
  'baby.accepted': 'Baby Mode activated. Don\'t worry — nobody has to know. ...Your share card will tell them, though.',
  'baby.declined': 'Respect. Idiotic, but respect.',
  'baby.early': 'Beg for mercy? You\'ve barely died! Come back at {n} deaths and we\'ll talk.',
  'baby.already': 'You\'re already in Baby Mode. There\'s no mode below this one. I checked.',
  'baby.on.fakecp': 'Baby Mode: that checkpoint actually saved. Disgusting.',
  'pause': [
    'Taking a break? The game isn\'t going anywhere. Neither is your death count.',
    'Pausing? Brave of you to take your eyes off me.',
    'Ah, a pause. A tactical retreat.',
  ],
  'resume': [
    'Welcome back. Miss me?',
    'Back already? I was just getting comfortable.',
  ],
  'idle': [
    'Are you still there? Blink twice.',
    'Take your time. I have nowhere to be. I\'m a voice in a game.',
    'This is the part where you move.',
    'I\'ll just stand here, then. Metaphorically.',
  ],
  'manualReset': [
    'Giving up already? Fine. Back we go.',
    'Resetting yourself? That\'s my job.',
  ],

  // ---------------------------------------------------------------- level 1 --------------
  'l1.welcome': 'Welcome to TRUST ME… the game show where you can trust me completely.',
  'l1.welcome2': 'I\'m your host. I\'ll be guiding you through today\'s course. I have never once lied to a contestant.',
  'l1.look': 'First: look around. Move your mouse. Go on. See? Everything is perfectly safe.',
  'l1.move': 'Now walk. W, A, S, D. The letters. On your keyboard. Take your time.',
  // touch twins (used instead of the keyboard lines on a phone or tablet)
  'l1.look.touch': 'First: look around. Drag your finger across the right side of the screen. Go on. See? Everything is perfectly safe.',
  'l1.move.touch': 'Now walk. Put your left thumb on the left side and push. Gently. Take your time.',
  'l1.gap.intro.touch': 'Time to jump! Tap the JUMP button. Tap for a hop, hold for the full jump. You\'re welcome.',
  'baby.offer.touch': 'You\'ve died {n} times. Here\'s a deal: BABY MODE. Higher jumps, longer coyote time, checkpoints that actually work. A permanent badge of shame. Tap the pink button to accept — or keep suffering.',
  'baby.offer.again.touch': 'Still suffering, I see. Baby Mode is still on the table. Tap the pink button. No one is judging. I am. But no one else.',
  'l1.walk': 'Wow. Natural. See the finish gate up ahead? Just walk right on in.',
  'l1.gate.1': 'Hm. The finish gate seems to have... moved.',
  'l1.gate.2': 'Construction. Totally normal. Keep walking!',
  'l1.gate.3': '...They\'re still setting up the finish. Walk faster.',
  'l1.gap.intro': 'Time to jump! Press SPACE. Tap for a hop, hold for the full jump. You\'re welcome.',
  'l1.gap.1': 'Look at you. A natural.',
  'l1.gap.2': 'Gap two. Bigger. Still easy. Everything is easy.',
  'l1.safe': 'That platform says SAFE. I would never lie on a sign.',
  'l1.crumble': '...Okay, that one\'s on the sign painter. Not me.',
  'l1.checkpoint': 'A checkpoint! Die, and you come back right here. Checkpoints are sacred. You can trust them. Completely.',
  'l1.beam': 'Narrow beam ahead. Don\'t look down. ...I said don\'t.',
  'l1.mover': 'A moving platform! Wait for it. Patience is a virtue. Not one you\'ve shown yet, but still.',
  'l1.exit.near': 'And that\'s the tutorial! You\'ve learned everything. Truly, a champion.',
  'l1.exit.reach': 'See? Totally fair. Tutorials always are. On to the real game. Trust me.',
  'l1.fall.first': 'Even the tutorial! That\'s a new one. For the tutorial, that is.',

  // ---------------------------------------------------------------- level 2 --------------
  'l2.intro': 'Welcome to Checkpoint Island! Five lovely checkpoints, every one of them trustworthy. Mostly.',
  'l2.tower': 'See that tower way over there? That\'s the finish. It\'s closer than it looks.',
  'l2.cp.real': ['Saved! Genuinely.', 'Checkpoint! That one\'s real. Would I lie?'],
  'l2.cp.fake': ['Saved! Isn\'t it nice to feel safe?', 'Progress saved. Take a deep breath. You\'ve earned it.'],
  'l2.cp.fake.reveal': 'Oh, that checkpoint? Fake. Did you not see the tilted pole? ...I told you to trust me. I never said I was trustworthy.',
  'l2.cp.fake.reveal2': 'And that one was fake too. You walked right into it. Twice. I\'m almost impressed.',
  'l2.mover': 'Timing is everything. And yet.',
  'l2.crumble': 'Don\'t stand still. It\'s not a rule. It\'s just good advice.',
  'l2.sweep': 'Those red things are sweeping lasers. They\'re purely decorative. Go on, touch one.',
  'l2.last': 'The very last jump. Five checkpoints, and I swear this one is real. ...You believe me, right?',
  'l2.complete': 'You did it! I\'m genuinely not sure how. Good for you.',

  // ---------------------------------------------------------------- level 3 --------------
  'l3.intro': 'The Tower. Climb to the top. If you fall, you land wherever gravity decides. Simple!',
  'l3.dontlook': 'Whatever you do, don\'t look down.',
  'l3.dontlook2': 'I said don\'t.',
  'l3.wind': 'A little breeze. Nothing to worry about. Hold on to your hat.',
  'l3.bee': 'Is that a bee on you? I\'d focus on the jump.',
  'l3.spider': 'Oh, that spider is huge. Anyway, jump.',
  'l3.checkpoint': 'A checkpoint! A real one. Please stop looking at the pole.',
  'l3.nocp': 'The next checkpoint is just ahead. Probably. I\'d have to check my notes.',
  'l3.fall': [
    'That was {m} metres of progress. Gone. Like it never happened.',
    '{m} metres down. The view is better from up there.',
    'You fell {m} metres. I measured. I measure everything.',
  ],
  'l3.fall.big': 'New record for falling! The leaderboard has been notified.',
  'l3.near': 'Almost there! Just a little more... wait, you\'re actually doing this.',
  'l3.last': 'This is the last jump. It\'s the hardest one. Also the one I tested the least. Good luck!',
  'l3.complete': 'Impossible. I mean — congratulations!',
  'l3.laser': 'The lasers here are totally harmless. Totally. Don\'t quote me.',

  // ---------------------------------------------------------------- level 4 --------------
  'l4.intro': 'Welcome to Technical Difficulties. Our engineers assure me everything is working perfectly.',
  'l4.loading': 'Please enjoy this loading screen. Keep walking — the game is still running.',
  'l4.loading.done': 'And we\'re back. See? Nothing bad happened.',
  'l4.controls': 'We\'ve updated your controls! For the better. Specifically, the left and the right.',
  'l4.controls.back': 'Controls restored. You\'re welcome. Or... sorry. One of those.',
  'l4.lag': 'Looks like you\'ve got a bad connection. In a single-player game. That takes talent.',
  'l4.lag.watch': 'Watch the ping. When it goes red, I\'d jump. Or don\'t. I\'m not your boss.',
  'l4.crash': 'We are experiencing technical difficulties. Please stand by.',
  'l4.crash.back': 'And we\'re back. I saved you four seconds you\'ll never get back.',
  'l4.ad': 'A word from our sponsor.',
  'l4.ad.skip': 'Skip in five. You can\'t. That\'s not a button.',
  'l4.counter': 'Your death counter looks off. I\'m sure it\'s fine.',
  'l4.pause': 'Resume? Just click it. Come on. Right there.',
  'l4.pause.touch': 'Resume? Just tap it. Come on. Right there.',
  'l4.pause.fine': 'Fine. Fine. You can have it.',
  'l4.complete': 'Level four done. The engineers have been told. They\'re fine. Everyone is fine.',

  // ---------------------------------------------------------------- level 5 --------------
  'l5.intro': 'You did it! Congratulations, contestant! Roll the credits!',
  'l5.credits.end': 'Thanks for playing!',
  'l5.credits.after': '...',
  'l5.curtain': 'Just kidding. Did you really think I\'d let it end that easily?',
  'l5.gauntlet': 'The finale! Everything you\'ve learned, all at once. Nothing you\'ve learned will help.',
  'l5.cp': 'That checkpoint is real. I swear on my... whatever I have.',
  'l5.lag': 'A little lag. For old times\' sake.',
  'l5.final': 'Two doors. The LEFT door is the real exit. Take the left door. Trust me.',
  'l5.win.right': '...You went right. You didn\'t trust me. I\'m so proud. And so, so furious.',
  'l5.win.wrong': 'The left door? Of course. You trusted me. Nobody ever learns.',
  'l5.cheat': 'I like how you\'re standing there, thinking. Enjoy it. It\'s the last peace you\'ll get.',
  'l5.complete': 'Credits. Real ones, this time. ...Mostly.',
};

// ---------------------------------------------------------------- hints ---
Object.assign(SCRIPT, {
  'hint.use': ['Oh, you need help? Of course you do. Follow the dots.', 'A hint! Free of charge. The dignity, however, will be billed later.', 'Fine. Follow the trail. Try not to die ON the trail.', 'Glowing dots. You\'re welcome. Please don\'t thank me.'],
  'hint.many': 'That\'s your fifth hint. I\'m starting a tab.',
  'hint.cooldown': 'Patience. Hints are a limited-time offer. Like my respect for you.',
  'hint.none': 'I have no hint for this one. That\'s not a lie. It\'s worse: it\'s a feeling.',
  'hint.hub': 'The lobby needs no hint. Walk toward the elevators. They\'re the big shiny doors.',
});

// ---------------------------------------------------------------- hotel (campaign 2) ---
Object.assign(SCRIPT, {
  'hotel.welcome': 'Welcome to Hotel Trust-Me. I\'m the manager. I was also the host. I wear many lies.',
  'hotel.welcome2': 'Check in at the elevators. Check out... we\'ll discuss it later.',
  'hotel.return': ['Welcome back to the lobby. Did you miss the marble? Everyone misses the marble.', 'Back so soon? The elevator remembers everything.'],
  'hotel.bell': ['*ding* How may I ignore you?', 'Service! ...is not available at this time.', 'Yes? No? Wrong bell.', 'You rang. I heard. That\'s all I\'m promising.'],
  'hotel.bell.many': 'If you ring that again, I am going to start charging you.',
  'hotel.doors': ['Check out? Hilarious. The doors are decorative.', 'Locked. For your safety. Mostly mine.', 'Those doors are for guests. You are a contestant. Different thing.'],
  'hotel.guestbook': ['Signed. You\'re checked in. Permanently.', 'Name noted. Debt noted. Welcome.'],
  'hotel.piano1': 'Lovely. Truly. Please stop.',
  'hotel.piano2': 'I\'m not paying for the piano tuner. Stop. It costs more than you do.',
  'hotel.out_of_order': ['That elevator is out of order. For you, specifically.', 'Out of order. Clear a floor first. I make the rules. I also lie about them.'],
  'hotel.locked_level': ['That level isn\'t open yet. Finish the previous one first. Yes, I\'m enjoying this.', 'Locked. Good things come to those who die repeatedly.'],
  'hotel.renovation': ['That floor is under renovation. It\'s been under renovation since the 90s.', 'Closed for renovation. The builders are... also contestants.', 'Floor not ready. The carpet is still lying about being finished.'],
  'hotel.elevator.go': ['Going up! ...probably.', 'Please hold on to something. Anything. Your dignity, maybe.', 'Next stop: consequences.'],
  'hotel.elevator.lie': ['Floor reached! Oh wait, no, that\'s the lobby. Again. My mistake. Not mine.', 'Ding! Lobby. Why are you surprised? The buttons are decorative.'],
  'hotel.l1.intro': 'Level one: Wet Floor. Housekeeping just mopped the lobby. All of it. With something that kills you.',
  'hotel.l1.intro2': 'Do not touch the floor. Use the furniture. It\'s what it\'s for. Probably. There are six stages. I will be here for all of them.',
  'hotel.l1.1': 'Hop on the ottoman. It\'s very comfortable. That\'s not a trap. This time.',
  'hotel.l1.mid': 'The piano! A checkpoint. Notice how I said "checkpoint" and not "safe". Words matter.',
  'hotel.l1.roll': ['Oh, that trolley has wheels. I said it was sturdy. Rolling is a kind of sturdy.', 'Whoops. Housekeeping never locks the brakes.', 'Fun fact: these trolleys go 5 km/h. You have about four seconds.'],
  'hotel.l1.mop': 'Meet the mop-bot. He is a good boy. He is also eighty kilos of yellow and he does not stop for guests. Hop him.',
  'hotel.l1.fakecp': 'Another checkpoint! Very official. Very straight. I would never lie to you about a flag. Look at it closely.',
  'hotel.l1.up': 'Now the cocktail tables. They\'re pedestal tables. Pedestal is French for "you will fall".',
  'hotel.l1.glide': ['Polished marble! Please don\'t stop. Stopping is where the falling happens.', 'Oh, did you want to stand still? On the wet marble? Adorable.', 'Slippery when wet. Slippery when dry. Slippery when you\'re the guest.'],
  'hotel.l1.gantry': 'The service gantry! It is only slightly higher than a lobby is allowed to be. Please keep moving. The gantry is, how shall I put it, tired.',
  'hotel.l1.swap': 'Ah. A software update. Your A and D keys have been swapped for your convenience. Just for a moment. It will pass. Like the gantry, if you are slow.',
  'hotel.l1.bridge': ['The bridge! It is perfectly solid. Right up until you are halfway across. I am not saying. I am just saying.', 'You may have noticed it shimmering. Marble does that. When it is thinking about leaving.'],
  'hotel.l1.near': 'Almost to the west wall. Do you hear that? That is the sound of me being proud. It is very quiet.',
  'hotel.l1.climb': 'Up the west side. The trays move. The trays have always moved. I did not tell you because you did not ask.',
  'hotel.l1.balcony': 'The mezzanine! There is the goal. And, look: an EXIT door. Both are right there. One of them is lying. I am not saying which. I am only a host.',
  'hotel.l1.closet': 'That is a broom closet. It has a lovely view of the floor. The floor you are about to meet. You are welcome.',
  'hotel.l1.hop1': ['It moved. The goal moved. I said it would be right there. I did not say it would stay there.', 'Oh dear. The goal is a little shy.'],
  'hotel.l1.hop2': 'It moved again! It does that. It is a goal with ambitions. One more time. I think. I have lost track. I wrote the rules.',
  'hotel.l1.fakewin': 'CONGRATULATIONS! You have completed the level! Please enjoy this screen for as long as it lasts.',
  'hotel.l1.bonus': 'Just kidding! Bonus stage! These platforms were not there a moment ago. They are very real. Go, go, go. The ceiling is high this time of year.',
  'hotel.l1.ad': 'A word from our sponsor! Trust Me Premium! Remove the host for just nine ninety-nine! The host cannot be removed! That is not a bug! It is a feature!',
  'hotel.l1.ad.after': 'And we are back. You did not watch it. I could tell. I tell everyone. Moving on to the gantry.',
  'hotel.l1.duster': ['The feather duster! A classic. It tickles. Fatally.', 'Dust is the real enemy. Housekeeping will tell you. Frequently. With a feather duster.'],
  'hotel.l1.dry': ['It said DRY. It had a tick. It was a very convincing tick. It was wrong.', 'That tile is only dry in the sense that it is a tile. The floor is the floor. The floor is everything.'],
  'hotel.l1.slip': ['Wet floor! The sign was right there. Several signs. In yellow.', 'You slipped. Housekeeping will mop you up.', 'The floor won. The floor always wins.', 'Caution means caution. You were not cautious.'],
  'hotel.l1.done': 'Done! You reached the top of the mezzanine. No one has ever been so wet and so proud. Not even me. I wrote the sign.',
  // ---- level 2 · Check-In (a quiz in six stages: see src/levels/hotel/check-in.js) ----
  'hotel.l2.intro': 'Level two: Check-In. A short registration form. Ten questions. I ask, you answer. By standing on the answer. Like a dignified sheep.',
  'hotel.l2.intro2': 'Stand on an answer for one second to sign it. Wrong answers get... corrected. Downwards.',
  'hotel.l2.r.honest': 'Question one is on the house. I will be completely honest with you: it is {letter}. Enjoy that. It is a limited edition.',
  'hotel.l2.r.lie': ['Question two. It is {letter}. I have never been so sure of anything. Look at my face. Is this the face of a man who checks?', 'Question two! {letter}. Definitely {letter}. I would put my name on it. Which name, is my business.'],
  'hotel.l2.r.slide': 'Question three. The answers slide. It is a feature. The feature is that you might miss.',
  'hotel.l2.r.timer': 'Question four! Fifteen seconds, starting now. When the clock says zero the answers go home. They have families.',
  'hotel.l2.ad': 'A short word from our sponsor. Five seconds. The question is not going anywhere. Neither are you.',
  'hotel.l2.r.none': 'And we are back. Question five. Read all four answers. All four. I mean it. Especially the last one.',
  'hotel.l2.r.flip': 'Question six. Read the top of the board. In red. I made it red so you would not read it.',
  'hotel.l2.wrong.flip': ['That was the RIGHT answer. This round wanted a WRONG one. It said so. In red.', 'Correct! Which is wrong. The board said pick a wrong answer. Reading is a skill.'],
  'hotel.l2.r.two': 'Question seven. Only ONE of these is right. The other one is a trap. A very good trap. I built it myself.',
  'hotel.l2.r.mind': 'Question eight. An easy one. Sign it, and I will open the gate. I am a man of my word. Usually the first word.',
  'hotel.l2.mind.check': ['Correct! The gate is open. Hold on. Let me just check the card.', 'Correct! Lovely. One moment, I am checking the card. Do not go anywhere.'],
  'hotel.l2.mind.flip': ['No. I have changed my mind. That answer is now wrong. Retroactively.', 'Actually, no. The card says no. Well, I say no. The card says nothing. It is a card.'],
  'hotel.l2.r.trust': 'Last question! Sign the register. Do you trust me? Say yes. Everybody says yes. It is the polite thing to say.',
  'hotel.l2.wrong.trust': ['You said yes. You trust me. After all this. That is adorable and also fatal.', 'Yes? YES? I am touched. You are falling. Both of these things are happening.'],
  'hotel.l2.right': ['Correct! Nobody is more surprised than I am.', 'Right! Savour it. It is rare.', 'Correct. The form accepts you. Barely.', 'Yes. I said that out loud. Moving on.'],
  'hotel.l2.wrong': ['Wrong. The pad has been informed.', 'Incorrect! Housekeeping will be right up. With a mop. For you.', 'No. Gravity will take it from here.', 'That is not the answer. That is a lifestyle choice.'],
  'hotel.l2.wrong.lie': ['You trusted me. That was the real wrong answer.', 'I said {letter}, yes. And you believed me. In this hotel.'],
  'hotel.l2.timeup': ['Time! The answers have left. They will be back in a moment. Try to be faster than them.', 'Zero! Off they go. Do not take it personally. They do this to everyone.'],
  'hotel.l2.hint': ['One wrong answer removed. A hint is just a lie you did not have to hear.', 'There. Fewer ways to fail. Not none. Fewer.', 'Done. One wrong answer gone. Still plenty left. I checked.'],
  'hotel.l2.hint.none': 'Only the right answers are left. Even I cannot help you now. I would not, either.',
  'hotel.l2.hint.mind': 'One wrong answer gone. And a free tip, which I resent: when I start checking the card, do not wait for me. Walk on.',
  'hotel.l2.hint.switch': 'One wrong answer gone. Tip: the question may change. Read it again when it does.',
  'hotel.l2.hint.double': 'One wrong answer gone. Tip: two answers are right. Stand on the line between them.',
  'hotel.l2.hint.flip': 'There. I took away the right answer. Which, this round, was the wrong one. Everything left is a wrong answer. Which is right.',
  'hotel.l2.hint.pass': 'One gone. Tip: nobody could know this. Not even you. Look around for another way.',
  'hotel.l2.hint.poll': 'One gone. Tip: the audience is a room full of chairs. Chairs do not know things.',
  'hotel.l2.hint.none.above': 'One gone. Tip, and I hate this: every answer on the board is wrong. Except one of them is not an answer.',
  'hotel.l2.switch': 'Ooh. The question has changed. That happens. Read it again. Quickly. The clock is not as patient as I am.',
  'hotel.l2.survey': 'Before we go on: a short survey. Your opinion matters to us. It matters in the sense that we count it.',
  'hotel.l2.trolleys': 'The luggage hall. Your bags went this way. So do you. Use the trolleys. They are very reliable. Most of the time. On rails.',
  'hotel.l2.shuttle': 'All aboard. It goes forward. It also goes back. Get off at the right end. Ends are important.',
  'hotel.l2.fakecp': 'A checkpoint! Very official. Look at that pole. Is it straight? It is straight enough. For me.',
  'hotel.l2.rack': 'Next, a trolley with no brakes. It is fine. It knows where it is going. I hope you do too.',
  'hotel.l2.roll': ['Wheee. It is going. Get off at the far end. Or stay on and come back. Either way, it is not my problem.', 'And off it goes. Housekeeping never locks the brakes. Hop off at the other side.'],
  'hotel.l2.door': 'The revolving door! Step on as it comes round, ride it half way, step off at the far side. It also does something to your controls. It is a revolving door. Things revolve.',
  'hotel.l2.swap': 'Left is right, right is left. That is what a revolving door does. Briefly. Walk forward, and nobody gets hurt.',
  'hotel.l2.r.breathe': 'Question eight. The pads breathe. In. Out. Sign on the way in, if you can.',
  'hotel.l2.carts': 'Two trolleys, passing. Hop onto the one coming your way. They do not stop. Neither do I.',
  'hotel.l2.door2': 'Another revolving door. This one turns the other way. I did not plan that. I did.',
  'hotel.l2.belt': 'The baggage belt. It runs the wrong way, for your convenience. Keep walking.',
  'hotel.l2.last': 'The last questions. Then the desk. Then you are checked in. Probably. Almost certainly. Mostly.',
  'hotel.l2.desk': 'The front desk! The goal is right there. Walk into it. You are checked in. I am not hiding anything. Look at my hands.',
  'hotel.l2.fakewin': 'CHECKED IN! Congratulations! Please enjoy this screen. It is your room key. Sort of.',
  'hotel.l2.register': 'Just kidding. You forgot to sign the register. Everyone does. Up the suitcases, please. Room 404 will wait. It always waits.',
  'hotel.l2.register.stage': 'The register. One last question. It is about us. Our relationship. Be honest. One of us has to be.',
  'hotel.l2.die.count': 'That is death number {n}. In a check-in. I am framing this one for the lobby.',
  'hotel.l2.die.door': ['The revolving door kept going. You did not. Step on when it comes round, step off when it gets there.', 'You left the door between floors. There are no floors. There is the door, and then there is down.'],
  'hotel.l2.die.trolley': ['Mind the gap between the trolley and the rest of your life.', 'The trolley went one way. You went the other. Down was not on the itinerary.'],
  'hotel.l2.done': 'You are checked in! Signed, sealed, distrustful. Your room is a lie, but the check-in was real. Enjoy your stay.',
  'hotel.l3.intro': 'Level three: Lost Luggage. You are locked in the baggage office. Which is not a metaphor. The door has a four-digit code.',
  'hotel.l3.intro2': 'The code is... let me check. {fake}. Yes. Definitely {fake}. I would not lie to a guest.',
  'hotel.l3.fake': ['{fake}? Really? I say a number and you type it in. That is called trust. It is a hobby of yours.', 'Access denied. By me. Mostly.'],
  'hotel.l3.denied': ['Access denied.', 'Wrong. Look around. The answer is not on my lips.', 'No. Try counting something. Anything.'],
  'hotel.l3.lock': 'Three wrong tries. The keypad needs a minute to think about what you have done.',
  'hotel.l3.granted': 'Access granted. Oh. I had that on a timer. Shame.',
  'hotel.l3.mimic': ['That one bites. It is in the brochure.', 'A mimic! Forty percent of suitcases are. Look it up.'],
  'hotel.l3.junk': ['A single sock. How tragic.', 'Nothing useful. I have been there.', 'Somebody\'s lunch. It is not fresh.'],
  'hotel.l3.ledger': 'The ledger says the code is {fake}. In my handwriting. I am the only one who writes in it.',
  'hotel.l3.belt': 'Baggage handling! The belts will carry you. Mostly backward. It is a lifestyle.',
  'hotel.l3.press': 'Oh, the baggage press. Do mind your head. And everything else.',
  'hotel.l3.done': 'Carousel 13! Your luggage is not on it. Nobody\'s ever is.',
  'hotel.l3.hint1': 'Hint: count the suitcases by colour. The poster says in what order.',
  'hotel.l3.hint2': 'Hint: the first two digits are {a} and {b}. The rest is counting. I am told you can do that.',
  'hotel.l3.hint3': 'Hint: the code is {code}. I am not lying. This once. Possibly.',
  'hotel.l4.intro': 'Level four: Revolving Door. The hotel has a rooftop hedge maze. It is not in the brochure. It is, however, in the lawsuits.',
  'hotel.l4.intro2': 'A new maze every time you try. The revolving doors run on a schedule. Not mine. Green lamp means go.',
  'hotel.l4.lie': ['Left. Always left. It is the rule of mazes.', 'I can see the exit from up here. It is straight ahead. I am looking at a different maze, but still.', 'Take the next right. Trust me. I have a map. It is upside down.'],
  'hotel.l4.deadend': ['A dead end! Every maze has one. Yours has several.', 'Nothing here but hedge and regret.', 'Congratulations, you found the part of the maze I am proudest of.'],
  'hotel.l4.half': 'Halfway! Statistically you are as lost as ever.',
  'hotel.l4.door': 'Revolving doors. A wonderful invention that lets you enter and leave at the same time. Mind the glass.',
  'hotel.l4.cart': ['Housekeeping has the right of way. It is in the contract.', 'You walked into a luggage cart. In a maze. Outdoors. Impressive.', 'Mind the trolley. It does not mind you.'],
  'hotel.l4.done': 'The exit! It was at the end the whole time. They always are. Mostly.',
  'hotel.l5.intro': 'Level five: Bellhop Blues. The bellhop is VERY keen to carry your bags. Over you, if necessary. He starts in a moment. Do not look back. Or do. It does not help either way.',
  'hotel.l5.intro2': 'Five stages. Five fire shutters. Each one slams behind you, and he waits behind it. Briefly. He is a professional.',
  'hotel.l5.go': 'DING DING DING. That is him. He does not do tips. He does feet.',
  'hotel.l5.bags': 'Laundry bags. Hop them. Housekeeping stacks them there to keep the guests in shape. And in the building.',
  'hotel.l5.express': ['The EXPRESS lane! Gold, glowing, complimentary. Take it. It is faster. I timed it myself.', 'Two belts. Take the gold one. Always take the gold one. That is just good taste.'],
  'hotel.l5.belts2': 'Did you take the express? Look at the little arrows on the belt next time. Arrows never lie. I do. Arrows do not.',
  'hotel.l5.expressdeath': ['The express runs backwards. Towards the bell. Express delivery. Of you.', 'You trusted the gold lane. The chevrons were pointing at you the whole time. Like everyone else in this hotel.'],
  'hotel.l5.marble': 'Wet marble over a bleach pit. Housekeeping calls it the slalom. The insurers call it something longer.',
  'hotel.l5.trolley': 'Oh, that trolley hangs from a rail. Rails go places. It is going. Off you get.',
  'hotel.l5.chute': 'The laundry chute! The only way on is down. Jump in. He will never fit down there. Probably. Bells are mostly round.',
  'hotel.l5.slam': ['SLAM. Fire shutter. Rated for two hours of fire. Rated for about four seconds of bell.', 'The shutter is down. He is behind it. Thinking about you.', 'Shut. Do not stand there admiring it.'],
  'hotel.l5.coming': ['Hear the shutter rattling? That is him knocking. He does not wait to be let in.', 'Rattle rattle. He is coming through. Move.'],
  'hotel.l5.burst': ['And there he is. Through the shutter. Two hours of fire rating, gone.', 'DING. Shutter? What shutter?'],
  'hotel.l5.chutebell': ['He fit. Bells are entirely round, it turns out.', 'DING. He came down the chute. Feet first. He has no feet.'],
  'hotel.l5.cp': ['Checkpoint! The bell has been notified. He took it personally.', 'Saved. He is behind the shutter. He is very patient. It is his best quality. His only quality.', 'Checkpoint. Breathe. Briefly.'],
  'hotel.l5.cp2': 'Checkpoint! Oh, and a small software update just went out. Mandatory. You will notice it. He will wait for it. He is considerate like that.',
  'hotel.l5.laundry': 'The laundry. The floor is suds. Industrial suds. Stay on the machines. They are very stable. Except the one on spin cycle.',
  'hotel.l5.fakecp': 'A checkpoint! Freshly laundered, perfectly pressed, completely straight. Look at that pole. Very straight. Do not look at that pole.',
  'hotel.l5.press': 'The steam press. Green lamp, go. Red lamp, flat. Amber lamp, you are already thinking too much.',
  'hotel.l5.twist': 'PATCH NOTES: W now walks backwards. S walks forwards. The bell still walks at you. It wears off. He is waiting either way.',
  'hotel.l5.staffexit': ['A staff exit! For staff! Oh, it is a closet. With no floor. Staff use it to leave in a hurry. Permanently.', 'That was a cupboard over a long drop. I did say STAFF. You are not staff. You are luggage.'],
  'hotel.l5.fryer': 'The fryer. Do not touch the oil. The trays slide. The oil does not. It just waits. Like him.',
  'hotel.l5.lamps': 'Heat lamps. Amber means they are warming up. White means you are.',
  'hotel.l5.mop': 'Just mopped! By the same people who did the lobby. Keep your momentum. Momentum is all you have.',
  'hotel.l5.reno': 'These stairs are under renovation. The builders took every other step. They said they would bring them back. That was in March.',
  'hotel.l5.gondola': 'The luggage gondola! It hangs from a rail. It has wheels on the rail. You can guess the rest.',
  'hotel.l5.elevator': 'The freight elevator! Staff only. Two thousand kilos. Step in and you are out. Trust me. This is the end.',
  'hotel.l5.fakewin': 'CONGRATULATIONS! Level five, complete! The elevator will now take you up to your reward.',
  'hotel.l5.outoforder': 'Ah. The elevator is out of order. It only goes one way. Down. Very, very down.',
  'hotel.l5.again': 'Still out of order. Still going down. Some things in this hotel you can rely on.',
  'hotel.l5.basement': 'The sub-basement. The boilers. Nobody comes down here. Except you. And, in a moment, him.',
  'hotel.l5.above': ['Listen. Up the shaft. That is not the elevator music.', 'Something is coming down the shaft. It is round. It is brass. It is late for you.'],
  'hotel.l5.shaftbell': 'He took the shaft. All of it. At once. DING.',
  'hotel.l5.steam': 'Steam pipes. The lamp goes amber, then the steam comes. I would not stand in the steam. I would not stand anywhere.',
  'hotel.l5.exit': 'The EXIT! Straight ahead! Green, glowing, enormous! You have done it! Run straight at it! Do not look at the crates!',
  'hotel.l5.painted': ['That EXIT was painted on the wall. By management. For you. The real way out was the dumbwaiter. Up the crates. The gold ring.', 'A painting of a door. You ran into art. The gold rings are real. The green ones are decorative. Mostly.'],
  'hotel.l5.caught': ['The bellhop has your bags. And you.', 'DING. Your luggage has arrived. It is you.', 'He is only doing his job. His job is you.', 'Flattened by a bell. That is death number {n} on this level. He is counting. Bells love counting.'],
  'hotel.l5.splash': ['Bleach. Suds. Oil. Cement. Boiling water. The back of house has every liquid except a nice one.', 'You fell in. Housekeeping will fish you out. Eventually. With a net.'],
  'hotel.l5.done': 'The dumbwaiter! Snug, dark and going up. You have been delivered. The bell is not allowed in. He does not have a reservation.',
  'hotel.l6.intro': 'Level six: Soufflé. The chef made a soufflé. A big one. It is rising. It does not care that you are in the kitchen.',
  'hotel.l6.intro2': 'Six stages up the kitchen. At the end of each there is a long steel counter. The soufflé stops under it and has a rest. It has earned it. It is mostly egg.',
  'hotel.l6.rise': 'And there it goes. Gently, at first. Never trust a dessert that is gentle.',
  'hotel.l6.pause': ['It has stopped. Under the counter. It is resting. Soufflés do that. Do not wake it.', 'Look at that. It will not climb past the counter you stand on. That is not a rule. That is manners.'],
  'hotel.l6.near': ['Close! It is rising. Soufflés do that. It is the entire personality.', 'You can smell it, right? Vanilla. And doom.'],
  'hotel.l6.tray': 'Serving trays! They slide. Hospitality is a moving target.',
  'hotel.l6.belt': 'The dishwasher belt. It runs towards you. Look at the chevrons. It has always run towards you. It is nothing personal.',
  'hotel.l6.s2': 'Stage two: the grill line. Steam, a pan, and a very honest EXIT. Stay on the left. The wall is on the left.',
  'hotel.l6.vents': 'Steam jets. The lamp goes amber, then red, then it is not a lamp problem any more.',
  'hotel.l6.exit': 'Look! An EXIT door! Right there on the wall! It is definitely an exit! Go on! Press E! Be brave!',
  'hotel.l6.pans': 'A swinging pan. Housekeeping calls it "a wall of cutlery". I call it Tuesday.',
  'hotel.l6.lag': ['Software update! Your jumps are now late. I do not know why. I am only the host. Press jump a little early.', 'Latency! The steam is slowing down the internet. Press early. It will wear off.'],
  'hotel.l6.fakeexit': ['That is the OVEN. The exit is up there. Where I pointed. The other way.', 'You walked into an oven. In a kitchen. And you are surprised.'],
  'hotel.l6.s3': 'Stage three: the burner bank. Hot plates on a beat. The ring goes amber before it goes white. Read the rings. Not me.',
  'hotel.l6.burner': 'Hot plates! Lit on a timer. I do not set the timer. The timer sets me.',
  'hotel.l6.liftsee': 'A SERVICE LIFT! On the east wall! Go on! It is a lift! Those exist!',
  'hotel.l6.lift': ['The service lift is a shaft. The shaft goes down. The soufflé is down. You see how it all fits together.', 'A lift! With no lift in it. A ring and a hole. Management is very proud of the ring.'],
  'hotel.l6.expired': 'Ah. Your checkpoint has expired. It said so. In small print. Everything here says so in small print.',
  'hotel.l6.s4': 'Stage four: the pastry counter. Cookie sheets. They crumble. It is what cookies do. This checkpoint is only good for twenty-eight seconds. Terms and conditions.',
  'hotel.l6.cookies': 'Cookie sheets! They go soft once you stand on them. Keep moving. Cookies are like that. So are guests.',
  'hotel.l6.cookie': 'The baking tray. It is cooling. Cooling things give way. It shimmers. Keep running. Do not think about it.',
  'hotel.l6.s5': 'Stage five: the pot rack. Everything slides now. Take your time. The soufflé is ten seconds behind you.',
  'hotel.l6.lie10': ['Do relax. It is ten seconds behind you. At least. Ten. I counted. Roughly. Do look down, though.', 'Ten seconds. Very comfortable. Wait on the steam if you like. It is only egg.'],
  'hotel.l6.slide': 'Everything on a rail! Pots on rails! The chef loves rails! He does not love you!',
  'hotel.l6.s6': 'The last stage. The roof access is right up there. I can see it. It is the only thing in this kitchen I would call a good idea.',
  'hotel.l6.top': 'The roof hatch! I can see it from here! It is the exact opposite of the soufflé: high, dry and not delicious.',
  'hotel.l6.roof': 'The hatch! Go on! Walk into the ring! It is over! You did it! Hand over the rest of your afternoon!',
  'hotel.l6.fakewin': 'It fell! The soufflé has FALLEN! Level complete! Hooray! Pack up! Go home!',
  'hotel.l6.bonus': 'Oh. It rose again. They do that. Soufflés. The real hatch is back down the room. Five steps. Quickly. Quietly. Mostly quickly.',
  'hotel.l6.foam': ['You have been folded in. That is a cooking term.', 'Soufflé: 1. You: a cautionary tale.', 'Delicious. For the soufflé.', 'It was ten seconds behind you. Now it is on top of you. I did say "roughly".'],
  'hotel.l6.burn': ['Hot. Hot hot hot. It was hot.', 'The pan has been pre-heated. By me. For you.', 'Medium rare. Mostly rare.', 'Steam. It is wet. It is also very hot. A tricky combination.'],
  'hotel.l6.fall': ['Down you go. The kitchen floor is very clean. Mostly because of the soufflé.', 'A long way down. A short way into the soufflé.'],
  'hotel.l6.done': 'The roof! It rose, you rose faster. Spiritually, you are now a pastry chef.',
  'hotel.l7.intro': 'Level seven: Trivia Night! Ten rounds. A live audience. And me, your dashing host, with the answers. Mostly.',
  'hotel.l7.intro2': 'Stand on an answer for one second to sign it. Wrong answers are removed, and so are you. Applause is mandatory.',
  'hotel.l7.r.honest': 'Round one. Easy. It is {letter}. I am being honest. I will be honest again, in a bit.',
  'hotel.l7.r.lie': ['Round two! The answer is {letter}. I have never been so sure. Write that down. Seriously, write that down.', 'Round two. {letter}. Without a doubt. I have no doubts. I checked, there are none left.'],
  'hotel.l7.r.slide': 'Round three. The pads are sliding. It is called "audience engagement". Keep your balance. And your dignity.',
  'hotel.l7.hop': 'Intermission! The chandeliers are free to use. They are not rated for use. Hop across, politely. Some of them are shy.',
  'hotel.l7.survey': 'Before the second half: a short survey about the evening so far. Your answer will be filed under "B".',
  'hotel.l7.vanish': 'Oh, that chandelier did not like you. Chandeliers are like that. Keep your feet moving next time.',
  'hotel.l7.expired': 'Your checkpoint has expired. It had a use-by date. In small print. On the flag.',
  'hotel.l7.r.timer': 'Round four! Twelve seconds. When the clock hits zero, the pads leave. I cannot stop them. I would not stop them.',
  'hotel.l7.r.four': 'Round five. Four answers! Whatever you do, do not pick {letter}. I would not pick {letter}. You know how I feel about {letter}.',
  'hotel.l7.r.call': 'Round six. Think back. At question two, which answer did I swear was correct? I said it clearly. I said it twice.',
  'hotel.l7.balcony': 'The balcony! A belt, some tiles, a cable. Please keep your hands, feet and dignity inside the venue.',
  'hotel.l7.mirror': 'Mirror mode! Left is right, for a moment. Walk forward. Mirrors do not judge. I do.',
  'hotel.l7.crash': 'We are experiencing technical difficulties. Please stand by. Do not touch the audience.',
  'hotel.l7.crash.after': 'And we are back. Nothing happened. Do not check.',
  'hotel.l7.final': 'The final three. No more tricks. That is a lie, the tricks were never the problem.',
  'hotel.l7.r.none': 'Round seven. Read ALL the answers. Then read the one that is not there.',
  'hotel.l7.r.double': 'Round eight. Double or nothing! Two answers are right. Stand on the line between them, one foot on each. Elegance is optional.',
  'hotel.l7.r.switch': 'Round nine. A simple one. Sign your answer. I will not be changing the question. I never change the question.',
  'hotel.l7.switch': 'Ooh. The question has changed. That happens. It is the show\'s fault. The show is me.',
  'hotel.l7.trophy': 'The trophy table! The goal is right there. Walk into it. You have won. Look at my hands, they are empty.',
  'hotel.l7.fakewin': 'CHAMPION! Congratulations! ...Hold on. The judges say it is a tie. With a ghost. We have to go to a tie-breaker.',
  'hotel.l7.tiebreak': 'A tie-breaker! The bridge is a gift from our sponsor. The sponsor is a chandelier.',
  'hotel.l7.r.poll': 'Tie-breaker. Let us ask the audience! The audience says {poll}. {pct} percent. The audience is furniture. Take that as you will.',
  'hotel.l7.right': ['Correct! The audience goes wild. The audience is a tablecloth. But still.', 'Right! Take a bow. A small one. Do not strain anything.', 'Yes! You are doing so well that I am worried about the ratings.', 'Correct. I was hoping you would not be.'],
  'hotel.l7.wrong': ['Wrong! Gasp! The audience gasps! The tablecloths flutter!', 'No. The correct answer is the other one. Obviously.', 'Incorrect! Please enjoy a little fall.', 'That is not right. That is not even close to right. That is right-adjacent.'],
  'hotel.l7.wrong.lie': ['You believed me. In round two. In THIS hotel.', 'I said {letter}. Out loud. On air. And you went with it.'],
  'hotel.l7.timeup': ['TIME! The pads have left. They are on break.', 'Time is up. That is the sound of the answers retiring.'],
  'hotel.l7.hint': ['One wrong answer, gone. Consider it a complimentary lie, reversed.', 'There. One fewer way to fail. We will find more.'],
  'hotel.l7.hint.none': 'Only the right answer is left. Even I cannot make this easier.',
  'hotel.l7.hint.switch': 'One wrong answer gone. Tip: the question may change when you sign. Read it again if it does.',
  'hotel.l7.hint.double': 'One wrong answer gone. Tip: two answers are right. Stand on the line between them.',
  'hotel.l7.hint.poll': 'One gone. Tip: the audience is a room full of chairs. Chairs do not know things.',
  'hotel.l7.hint.none.above': 'One gone. Tip, and I hate this: every answer on the board is wrong. One of the pads is not an answer, though.',
  'hotel.l7.die.count': 'That is death number {n}. In a quiz. I am putting it on the scoreboard. Under "Contestants".',
  'hotel.l7.die.hop': ['The chandelier swung one way. You went the other. It happens to the best of us. Mostly to you.', 'Chandeliers are decorative. I thought I mentioned that.'],
  'hotel.l7.die.belt': ['The belt does not care. It is a belt. Walk faster than it does.', 'Cables are for walking over, not into. A cable is a very small fence.'],
  'hotel.l7.done': 'You are the champion! The trophy is plastic. The title is real. The prize is... this moment.',
  'hotel.l8.intro': 'Level eight: Dinner Is Served. You have been invited to dinner. You are not on the menu. Yet.',
  'hotel.l8.intro2': 'Our guest is very hungry and very particular. The menu on the wall says the order. Between us, I say serve the {first} first. Tradition.',
  'hotel.l8.first': 'One down. The guest nods. He has no neck. It is a very subtle nod.',
  'hotel.l8.half': 'Halfway through the courses. The guest is thrilled. You can tell by the absolute lack of expression.',
  'hotel.l8.open': 'All six courses served in order. The kitchen door opens. I am furious. Mostly with the order.',
  'hotel.l8.dessert': ['DESSERT FIRST?! Then you shall have it. All of it. From above.', 'Dessert is last. Everyone knows that. Look out.'],
  'hotel.l8.wrong': ['Wrong course! The trolley has been dispatched. Look up. Or sideways. Quickly.', 'Out of order! The kitchen has strong feelings. They are about to be delivered.', 'That was not the next course. Brace yourself, a cake has been notified.'],
  'hotel.l8.cellar': 'The wine cellar. It is where we keep the good stuff and the questionable decisions.',
  'hotel.l8.merlot': 'Someone spilled the Merlot. Somebody. Who? Do not look at me. Do look at your feet.',
  'hotel.l8.barrel': ['A barrel! They roll! It is in the name! Well, it is in the physics.', 'Flattened by a barrel of something nice. Cheers.', 'Barrel one, you nil. A classic.'],
  'hotel.l8.done': 'The kitchen! You made it through the entire meal without eating. The guest has left you a tip. It is a sock.',
  'hotel.l8.hint1': 'Hint: the menu on the wall describes each course in a riddle. They are in the order to serve them. Not the order I said.',
  'hotel.l8.hint2': 'Hint: first the {a}, then the {b}. After that you are on your own. Which is the usual arrangement.',
  'hotel.l8.hint3': 'Hint: the order is {all}. I am not lying. Obviously I would say that if I were.',
  'hotel.l9.intro': 'Level nine: Kitchen Maze. Walk-in freezers, one-way doors, and a chef. He is not here yet. Do not wait for him to arrive.',
  'hotel.l9.intro2': 'A different maze every time. The freezers are slippery. The chef is not. Dead ends are a bad idea. I mention it as a courtesy.',
  'hotel.l9.go': 'He has noticed you. Chefs notice everything. Especially texture.',
  'hotel.l9.near': ['He is right behind you. He has a very large knife and a very small sense of humour.', 'Can you hear that? That is the sound of professional commitment.'],
  'hotel.l9.oneway': 'One-way doors! Hygiene regulations. Cross-contamination, you see. Of you. Into the rest of the building.',
  'hotel.l9.ice': 'The freezers. Slippery. That is for food safety. Not yours.',
  'hotel.l9.lie': ['Left. It is definitely left. I used to work here.', 'Straight on! The exit is straight on! I am looking at a different kitchen, but still.', 'Take the next right. A chef told me. Not this one.'],
  'hotel.l9.caught': ['Chopped. Julienned, even.', 'You have been served. By the chef. To himself.', 'Tonight\'s special: you. Medium rare.', 'He caught you. He is not even out of breath. He is out of patience.'],
  'hotel.l9.done': 'The loading dock! You escaped the kitchen. The chef is not angry. He is disappointed. And hungry.',
  'hotel.l10.intro': 'Level ten: Dance Floor. The tiles blink to the beat. I do not control them. The DJ does. The DJ is also me.',
  'hotel.l10.intro2': 'Five sets. A booth after each. Hop from lit tile to lit tile. When I shout FREEZE, you freeze. Mostly. Listen to the lights.',
  'hotel.l10.tiles': 'Tiles! They blink. A tile that flickers is about to go. A tile that is dark is not a tile. It is a fall with a nice colour.',
  'hotel.l10.warn': ['Freeze! Everybody freeze! In a moment! Statues! Do not twitch!', 'Statues in three... two... one...'],
  'hotel.l10.freeze': 'FREEZE. Every light goes red. Not a single step. Not a wiggle. Pretend you are a decorative urn.',
  'hotel.l10.moved': ['You MOVED. During the freeze. That is the entire game, and you moved.', 'Statues do not walk. You were a bad statue.', 'I said freeze. The lights said freeze. Even the ball said freeze.'],
  'hotel.l10.s2': 'The second set! Faster, smaller, and I have a surprise. The surprise is that I said it was a surprise.',
  'hotel.l10.faster': 'Smaller tiles now. Because the song is getting good. And the gold pad is a gift. Do step on it. Please.',
  'hotel.l10.skip': ['Oh! I dropped the beat! It happens to the best of us. It does not happen to me. It happened now.', 'The beat just skipped. The tiles are half a beat late. Listen for the hat. It has moved house.'],
  'hotel.l10.bluffwarn': ['FREEZE! Everybody freeze! Right now! Stand absolutely still! I mean it! I have never meant anything more!', 'Statues! Statues! Statues! Do not move a muscle!'],
  'hotel.l10.bluffend': 'Ha! Did you stop? The lights did not go red. Not one. A very good freeze has red lights. You are a very good statue.',
  'hotel.l10.s3': 'The conga line! Join it. It will not wait. It will wiggle. That is the entire dance.',
  'hotel.l10.conga': 'Conga platforms! They snake from side to side. Follow the one in front. Everyone does. That is the joke.',
  'hotel.l10.mirror': ['Mirror mode! Look left, turn right. It is a feature of the strobes. It wears off. So does the strobe.', 'The strobes make everything backwards. Science. Mostly. Keep hopping.'],
  'hotel.l10.s4': 'The spotlight floor! When I shout SPOTLIGHT, stand in the circle. The floor goes red outside it. It is not subtle. I am not subtle.',
  'hotel.l10.floor': 'A big floor! Empty! Safe! Lovely! Enjoy it. In a moment I will point a light at it.',
  'hotel.l10.spot1': ['SPOTLIGHT! In the circle! The circle! Do not look at me, look at the circle!', 'Spotlight in three, two... get in the light!'],
  'hotel.l10.spot2': ['SPOTLIGHT again! It is a very popular light. Get in it!', 'And the light moves! Follow the light! Always the light!'],
  'hotel.l10.spotdeath': ['Out of the light. In the dark. At the party. That is the whole review.', 'The floor was red. The circle was white. You chose neither.'],
  'hotel.l10.s5': 'The mirror ball bridge! A very short walk. The tiles hold for exactly as long as you do not stop. Keep walking. Elegantly.',
  'hotel.l10.bridgesee': 'The bridge shimmers. That is not the lighting. That is a warning. Keep running, you magnificent mover.',
  'hotel.l10.bridge': 'It is going! The tile is going! Do not stop! You are doing fine! You are doing a fall!',
  'hotel.l10.dj': 'My booth! The DJ booth! The best seat in the house. Go on, touch the ring. Everyone does.',
  'hotel.l10.vip': 'Ooh, the VIP lounge! Very exclusive. Only the best guests. Go on. Walk in. You are certainly a very important person.',
  'hotel.l10.vipdeath': ['The VIP lounge is a hole. It has always been a hole. The exclusivity is the drop.', 'Nobody is in the VIP lounge. That is how you know it is exclusive. And deep.'],
  'hotel.l10.djcp': 'Checkpoint at the booth. Almost done. The ring is right there. It is the finish. Probably.',
  'hotel.l10.fakewin': 'LEVEL COMPLETE! You danced! Congratulations! Go on! Collect your trophy! It is a very good trophy!',
  'hotel.l10.encore': 'AN ENCORE! The crowd demands it! The crowd is me! The tiles are faster! Do not stand on anything for long!',
  'hotel.l10.fall': ['Out of rhythm. Out of tiles. Out of luck.', 'The tile left. It had somewhere to be.', 'You were two beats late and the floor was on time.'],
  'hotel.l10.done': 'The encore is done! You are officially a dancer. Please stop moving. The freeze never really ends.',
  'hotel.l11.intro': 'Level eleven: Room 404. Your room. We found it. We lost it. We found it again. It is... slightly different from last time.',
  'hotel.l11.intro2': 'The door has a three-digit code. The digits are in the furniture. The furniture is shy. It moves when you are not looking at it. I mention that for no reason.',
  'hotel.l11.moved': 'Did that dresser just... no. No, it did not. You are tired. Furniture is famously stationary.',
  'hotel.l11.ward': 'Oh, and the wardrobe. It is very old. It is also very curious. Do not take your eyes off it. I would not say that if I did not care. I do not care.',
  'hotel.l11.close': ['It is getting closer. Look at it. LOOK AT IT.', 'Stop looking at the dresser. Look at the wardrobe. The wardrobe is the one.'],
  'hotel.l11.dark': 'Maintenance! The lights are out. That is not a euphemism. Mind the wardrobe.',
  'hotel.l11.first': 'One digit. Two to go. And a wardrobe to keep an eye on. Both eyes, ideally.',
  'hotel.l11.second': 'Two digits. You are doing so well. The wardrobe is proud. It does not say so.',
  'hotel.l11.all': 'All three digits! Now the door. It is the one with the number on it. 404. Not found. Found.',
  'hotel.l11.note': 'A note from the armchair: "The code is 404." Signed: me. Naturally I would never lie to a guest.',
  'hotel.l11.fake': ['404? Room 404, code 404. It would be so tidy. It is also wrong.', 'Not found! That is what 404 means. Nice try.'],
  'hotel.l11.denied': ['Wrong code.', 'The door does not like that one.', 'No. Try the furniture.'],
  'hotel.l11.lock': 'Three tries. The keypad has locked itself. For your own good. It is mostly spite.',
  'hotel.l11.caught': ['The wardrobe has got you. It has a very big door. You are inside now.', 'You looked away. Everybody looks away. That is how it wins.', 'Wardrobe: 1. You: a hanger.'],
  'hotel.l11.open': 'The door is open! Run! Do not look back! It cannot move if you look, but it can if you do not! Oh, I cannot decide.',
  'hotel.l11.done': 'Out! You left Room 404. It will be there, unseen, behind you. Do not look back.',
  'hotel.l11.hint1': 'Hint: search the furniture. Three of the four pieces hold a digit. And keep an eye on the wardrobe. Both eyes.',
  'hotel.l11.hint2': 'Hint: the bed, the desk and the dresser each hold a digit. The armchair holds a lie. I know which one is which. I am not saying.',
  'hotel.l11.hint3': 'Hint: the code is {code}. And no, it is not 404.',
  'hotel.l12.intro': 'Level twelve: Do Not Disturb. Housekeeping is on the floor. Two of them. They have a very strict policy about guests who are not in their rooms.',
  'hotel.l12.intro2': 'They see in a cone. I have helpfully drawn it on the floor. Do not stand in it. If you must, hide in a laundry cart. They are in the dead ends. Obviously.',
  'hotel.l12.hide': 'Hidden! In a cart! Among the sheets! Which are, I should say, not entirely clean. Press anything to climb out.',
  'hotel.l12.spotted': ['She has seen you! Run! Or, better, stop being in the cone.', 'Uh oh. That is the look of someone who has found a guest in a corridor.'],
  'hotel.l12.caught': ['Housekeeping! You are in the wrong place at the wrong time. In the right hotel, though.', 'Seen! Caught! Folded and put in the cupboard.', 'No Do Not Disturb sign can save you now. There was never one on you.'],
  'hotel.l12.found': ['She found you in the cart. She was looking for more sheets. You were more sheets.', 'The cart is hers. The cart is always hers. You were, briefly, laundry.'],
  'hotel.l12.lie': ['Left! Always left! I have worked here for years! In a different building!', 'The exit is right there! Straight on! I can see it! It is a different exit!', 'Do Not Disturb signs mean they will not come in. That is what the sign says. It does not say anything about corridors.'],
  'hotel.l12.cart': 'A laundry cart. Climb in. It is the only discreet thing in this hotel.',
  'hotel.l12.done': 'The stairs! Nobody saw you. Nobody ever does. It is the hotel industry\'s greatest strength.',
  'hotel.l13.intro': 'Level thirteen: Minibar. A quiz. The answers are in the minibars. Every minibar has a price. The price on the door is the price. Before the rest.',
  'hotel.l13.intro2': 'You have eighty dollars. A deposit. Opening a minibar costs four. Plus the things. Hints cost nine ninety-nine. Plus the things. You can also just guess. For free. I will be so disappointed.',
  'hotel.l13.first': 'Your first minibar! It cost four dollars. And some other dollars. I will itemise later. Maybe.',
  'hotel.l13.opened': ['Another one! You are a high roller. A mid roller. A roller.', 'Opened. The fees are delighted to meet you.', 'The door said four dollars. The door has a lovely sense of humour.'],
  'hotel.l13.declined': ['Card declined! You have been very generous with my money. I mean yours.', 'Insufficient funds. The minibar is closed. Guess like it is the nineties.', 'No funds, no fridge. Statistically you were only wrong on purpose.'],
  'hotel.l13.comp': 'Oh, fine. The fee is waived, once. Compassion is a line item. It will appear on the bill.',
  'hotel.l13.card': 'Card declined. There is nothing wrong with the card. The card is simply not in the mood. Please complete a short survey, and try again.',
  'hotel.l13.skip': 'You skipped the ad for ninety-nine cents. Plus the things. The ad is sad. I am not.',
  'hotel.l13.r.honest': 'Round one. Not a trick question. The answer is {letter}. I can say that without opening a fridge. Open it anyway. The door is so proud of its price.',
  'hotel.l13.r.lie': ['Round two. It is {letter}. I would not charge you for the truth. Not on the first lie.', 'Round two! {letter}. Easy. I read it off the fridge. The fridge is never wrong. The fridge is also not here.'],
  'hotel.l13.r.breathe': 'Round three. The pads breathe. Hospitality is mostly motion. Sign on the way in.',
  'hotel.l13.r.timer': 'Round four! Eleven seconds! The minibar would like to remind you that opening it is free for the first second. That is also a lie.',
  'hotel.l13.queue': 'The checkout queue! Everyone leaves eventually. Not everyone leaves in one piece. Mind the luggage. It has right of way.',
  'hotel.l13.glitch': 'The self-checkout is having a moment. Left is right, right is left. Walk forward. Nothing scans.',
  'hotel.l13.next': 'Next please! The lift runs between the lanes. Wait for it. Queues are just waiting with a floor plan.',
  'hotel.l13.tab': 'Act two: the tab. Prices go up. Patience goes down. The minibar is a business, and you are the business.',
  'hotel.l13.r.slide': 'Round five. The pads slide. The fridge is locked, in case you wanted to feel something. Open it. Pay. Feel it.',
  'hotel.l13.survey': 'Before we continue: a short survey. We would like to know how you feel about your declined card. The answer is "declined".',
  'hotel.l13.r.poll': 'Round six. Let us ask the audience. The audience says {poll}. {pct} percent. The audience is on the minibar payroll.',
  'hotel.l13.r.flip': 'Round seven. Read the top of the board. In red. I made it red so you would not read it.',
  'hotel.l13.wrong.flip': ['That was the RIGHT answer. This round wanted a WRONG one. It said so. In red.', 'Correct! Which is wrong. The board said pick a wrong answer. Reading is a skill. A billable skill.'],
  'hotel.l13.ad': 'A word from our sponsor. Press K to skip it for ninety-nine cents. Plus the things. Or stand there. It is free. It is five seconds of your life, which is also on the bill.',
  'hotel.l13.r.none': 'Round eight. Read ALL the answers. Then read the one that is not there. It is not free. Nothing is.',
  'hotel.l13.carousel': 'The luggage carousel! Your bags go round. So does the belt. Stay left of the bags and right of the edge.',
  'hotel.l13.lure': 'A checkpoint! Over there! On the little platform! Just for you! It is entirely safe. I am pointing at it. With my whole face.',
  'hotel.l13.rewind': 'Checkpoint saved! And now you are over there. Back where you started. Time is a flat circle. With fees.',
  'hotel.l13.vanish': 'A quick-release plank. It releases quickly. Keep walking and it will not be your problem.',
  'hotel.l13.settle': 'Act three: settling up. Four rounds. Then the bill. Then you leave. Nothing could possibly be added after that.',
  'hotel.l13.r.double': 'Round nine. Double or nothing. Two answers are right. Stand on the line between them. The line is free. The nothing is not.',
  'hotel.l13.r.switch': 'Round ten. A simple one. Pay for the minibar, read it, sign it. I will not change the question. I never change the question.',
  'hotel.l13.switch': 'Ooh. The question has changed. That happens. Housekeeping moves things. Housekeeping is me.',
  'hotel.l13.r.mind': 'Round eleven. An easy one. Sign it and I will open the gate. I am a man of my word. Usually the first word.',
  'hotel.l13.mind.check': ['Correct! The gate is open. Hold on. Let me just check the card.', 'Correct! Lovely. One moment, I am checking the card. Do not go anywhere.'],
  'hotel.l13.mind.flip': ['No. I have changed my mind. That answer is now wrong. Retroactively. With a fee.', 'Actually, no. The card says no. Well, I say no. The card is a card.'],
  'hotel.l13.r.pass': 'The last question! Nobody could know this. Not you. Not me. Not the minibar. Look around. Someone left a way out.',
  'hotel.l13.desk': 'The front desk! Time to check out. Press E at the desk. Read the bill. Pick a tip. There is no "no tip". I looked.',
  'hotel.l13.bill': 'Your bill! Please review it. Carefully. You will be reviewing it for a while. Pick a tip. Any tip. As long as it is a good one.',
  'hotel.l13.fakewin': 'CHECKED OUT! Thank you for staying with us! We hope you enjoyed... hold on. Accounting is on the phone.',
  'hotel.l13.correction': 'A correction. There is a second bill. A late one. Through the fee gate, please. It is not a bridge. It is a payment plan.',
  'hotel.l13.late': 'Late fees. They are called that because they arrive late. They arrive. Keep moving, they have a way of piling up.',
  'hotel.l13.bill2': 'The corrected bill. Same as the first one, but louder. Pick a tip. A bigger one this time. For the inconvenience of the correction.',
  'hotel.l13.right': ['Correct. A fee for being correct has been added. It is small. It is my favourite fee.', 'Right! Do not let it go to your head. Heads are extra.', 'Yes! Another one. At this rate you will break even. Just kidding. You will not.'],
  'hotel.l13.wrong': ['Wrong! Please enjoy a complimentary fall. It is on the house. The fall, not the floor.', 'Incorrect! We have already added a fee for it.', 'No. The correct answer was in the minibar. You did not open the minibar.'],
  'hotel.l13.wrong.lie': ['You believed me about the letter. Even after the minibar. Even after the FEES.', 'I said {letter}. I say a lot of things. You pay for most of them.'],
  'hotel.l13.timeup': ['TIME! The pads have checked out. They left a review.', 'Out of time. The clock is paid for. You are not.'],
  'hotel.l13.hint': ['One wrong answer removed. Nine ninety-nine. Plus things. Worth every cent of the things.', 'Done. Hint fee: reasonable. Hint fee plus the other fees: not so much.'],
  'hotel.l13.hint.none': 'Only the right answer is left. We cannot sell you any more help. We tried.',
  'hotel.l13.hint.mind': 'One wrong answer gone. And a free tip, which I resent: when I start checking the card, do not wait for me. Walk on.',
  'hotel.l13.hint.switch': 'One wrong answer gone. Tip: the question may change when you sign. Read it again when it does.',
  'hotel.l13.hint.double': 'One wrong answer gone. Tip: two answers are right. Stand on the line between them.',
  'hotel.l13.hint.flip': 'There. I took away the right answer. Which, this round, was the wrong one. Everything left is a wrong answer. Which is right.',
  'hotel.l13.hint.pass': 'One gone. Tip: nobody could know this. Look around for another way.',
  'hotel.l13.hint.poll': 'One gone. Tip: the audience is a room full of chairs. Chairs do not know things.',
  'hotel.l13.hint.none.above': 'One gone. Tip, and I hate this: every answer on the board is wrong. One of the pads is not an answer, though.',
  'hotel.l13.die.count': 'That is death number {n}. In a hotel quiz. We have added a fee for it. It is a fee for the fee.',
  'hotel.l13.die.queue': ['The luggage has right of way. It is in the contract. You signed it. With your feet.', 'The queue moved. You did not. Nobody has ever been so far behind.'],
  'hotel.l13.die.carousel': ['The carousel keeps going. You did not. That is the difference between luggage and guests.', 'Bags go round and round. Guests go down. It is in the brochure.'],
  'hotel.l13.expired': 'Your checkpoint has expired. It had a use-by date. In small print. On the flag.',
  'hotel.l13.done': 'Thank you for staying with us! We have charged you for the thank-you.',
  'hotel.l14.intro': 'Level fourteen: Hallway Loop. One corridor. Walk it. If everything is normal, keep going to the end.',
  'hotel.l14.intro2': 'If ANYTHING is different, turn around and walk back. Get it right {need} times in a row and I will let you out. Get it wrong and you start again. I will have opinions the whole way.',
  'hotel.l14.host.same': ['Looks normal to me. Go on.', 'Nothing different here. I would know. I live here.', 'Perfectly ordinary. Carry on.'],
  'hotel.l14.host.diff': ['Hm. Something is different. I can feel it. Go back.', 'I would turn around, if I were you. There is something. I will not say what.', 'That is not how I left it. Back you go.'],
  'hotel.l14.first': 'One! Right! Do not let it go to your head. You have five more. And I have all the time.',
  'hotel.l14.right': ['Correct! The hallway is so annoyed.', 'Right again! How, though?', 'Another one. The corridor is sweating.'],
  'hotel.l14.last': 'That is all of them. All six. You did it. I am so, so angry. The way out is opening.',
  'hotel.l14.missed': ['There WAS something. You walked right past it. In a hallway. With one thing in it.', 'Wrong! Back to zero. Look more. Blink less.', 'It was RIGHT THERE. And you were so confident. I am only a little moved.'],
  'hotel.l14.paranoid': ['There was nothing! You turned back from NOTHING. You were hallucinating. Hotels do that.', 'It was normal. You were paranoid. That is a fair reaction to this hotel, but still wrong.', 'Nothing was different. You imagined it. Back to zero.'],
  'hotel.l14.open': 'The north end has... changed. Yes. There are stairs. They were not there a moment ago. Stairs are like that.',
  'hotel.l14.hint.none': 'Hint: nothing is different. Keep walking forward. I have, this once, no reason to lie.',
  'hotel.l14.hint.some': 'Hint: there is something different in the corridor. Turn around when you find it. I will not tell you what. Press H again if you must.',
  'hotel.l14.hint.where': 'Hint: {where}',
  'hotel.l14.done': 'Out! The hallway is still looping, for the next guest. It has a lot of patience. And a lot of paintings.',
  'hotel.l15.intro': 'Level fifteen: Window Ledge. We are outside the hotel. Eleven floors up. In a thunderstorm. Because I could not find the other door.',
  'hotel.l15.intro2': 'Window to window along the ledges. The wind will push you off the wall in gusts. Lean into the wall. The wall is the one that is solid.',
  'hotel.l15.wind': 'Gusts! They push you away from the building. Lean in. Press the key that goes toward the wall. Which is, helpfully, the one I did not say.',
  'hotel.l15.ac': 'Air conditioners! They are very stable. They are bolted to a very old wall. Do not think about the wall.',
  'hotel.l15.crumble': 'These sills have been here since eighteen ninety. They are tired. They would like to retire, now, under you.',
  'hotel.l15.pipe': 'A pipe. Balance on it. Gymnasts do it on a beam. A beam is wider. And indoors. And there is no thunderstorm.',
  'hotel.l15.gondola': 'The window cleaner\'s gondola! He is on his break. His break has lasted since March. Hop on when it is close.',
  'hotel.l15.gargoyle': 'Gargoyles! Lovely craftsmanship. They are not meant to be stood on. They are not meant to be stood on by you in particular.',
  'hotel.l15.fall': ['Eleven floors. A long way down. The shorter way is not available.', 'You have left the building. Not in the way I intended.', 'The wind won. The wind always wins. It is the wind.', 'Splat is a word. It is also, I regret to say, the outcome.'],
  'hotel.l15.done': 'The window! It is open! It is a staff closet! It has mops! It is the best room in the hotel!',
  'hotel.complete.first': 'Level one done! The marble is very proud of you. I\'m... fine.',
});

export const CREDITS = [
  ['TRUST ME…', ''],
  ['Written, directed & narrated by', 'The Host'],
  ['Starring', 'You (barely)'],
  ['Falling', 'Also you'],
  ['Checkpoint department', 'Mostly honest'],
  ['Physics supervisor', 'Gravity'],
  ['Trust & Safety', 'Not available'],
  ['Lasers', 'Decorative'],
  ['Special thanks', 'Your mouse. Your patience. My ego.'],
  ['No contestants were harmed', 'Several were annoyed'],
];
